---
site_name: Sagan
repo_url: https://github.com/kgaughan/sagan/
theme:
  name: material

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite: {}
  pymdownx.snippets: {}
  pymdownx.superfences: {}
  admonition: {}
  attr_list: {}

nav:
  - index.md
